// <auto-generated />
using System;
using BeerApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeerApi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlcoholContent")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("BreweryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlcoholContent = 6.6m,
                            BreweryId = 1,
                            Description = "Uma ale abacial suave e equilibrada com notas de especiarias e baunilha.",
                            Name = "Leffe Blonde",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            AlcoholContent = 6.5m,
                            BreweryId = 1,
                            Description = "Uma ale abacial escura e encorpada com notas de caramelo e chocolate.",
                            Name = "Leffe Brune",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            AlcoholContent = 8.5m,
                            BreweryId = 1,
                            Description = "Uma triple dourada e forte com caráter frutado e condimentado complexo.",
                            Name = "Leffe Triple",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            AlcoholContent = 7.0m,
                            BreweryId = 2,
                            Description = "Chimay Tampa Vermelha — um clássico dubbel trapista com notas frutadas e carameladas.",
                            Name = "Chimay Rouge",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 5,
                            AlcoholContent = 9.0m,
                            BreweryId = 2,
                            Description = "Chimay Tampa Azul — uma ale escura encorpada e complexa com frutas escuras.",
                            Name = "Chimay Bleue",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 6,
                            AlcoholContent = 8.0m,
                            BreweryId = 2,
                            Description = "Chimay Tampa Branca — uma Tripel dourada com final seco e lupulado.",
                            Name = "Chimay Triple",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 7,
                            AlcoholContent = 8.5m,
                            BreweryId = 3,
                            Description = "A icônica ale dourada forte belga — 'diabo' em flamengo.",
                            Name = "Duvel",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 8,
                            AlcoholContent = 4.7m,
                            BreweryId = 3,
                            Description = "Uma wit beer belga refrescante com notas de cítrico e coentro.",
                            Name = "Vedett Extra White",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 9,
                            AlcoholContent = 7.0m,
                            BreweryId = 4,
                            Description = "Um clássico dubbel trapista com malte rico, frutas escuras e final seco.",
                            Name = "Westmalle Dubbel",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 10,
                            AlcoholContent = 9.5m,
                            BreweryId = 4,
                            Description = "O estilo Tripel original — dourado, forte e maravilhosamente complexo.",
                            Name = "Westmalle Tripel",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 11,
                            AlcoholContent = 7.5m,
                            BreweryId = 5,
                            Description = "O mais leve da linha Rochefort, ainda lindamente complexo com frutas âmbar.",
                            Name = "Rochefort 6",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 12,
                            AlcoholContent = 9.2m,
                            BreweryId = 5,
                            Description = "Ale escura rica e complexa com ameixas, figos e uma força reconfortante.",
                            Name = "Rochefort 8",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 13,
                            AlcoholContent = 11.3m,
                            BreweryId = 5,
                            Description = "Uma das maiores cervejas do mundo — profundamente complexa, reconfortante e satisfatória.",
                            Name = "Rochefort 10",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 14,
                            AlcoholContent = 8.5m,
                            BreweryId = 6,
                            Description = "Mundialmente famosa ale dourada forte com a característica garrafa do elefante rosa.",
                            Name = "Delirium Tremens",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 15,
                            AlcoholContent = 5.2m,
                            BreweryId = 7,
                            Description = "Um lager belga premium, fresco e refrescante, produzido desde 1926.",
                            Name = "Stella Artois",
                            Price = 1.80m
                        },
                        new
                        {
                            Id = 16,
                            AlcoholContent = 4.9m,
                            BreweryId = 7,
                            Description = "A witbier belga original, produzida com coentro e casca de laranja.",
                            Name = "Hoegaarden",
                            Price = 2.20m
                        });
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Brewery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Bélgica",
                            Description = "Famosa cervejaria de estilo abacial estabelecida em 1152, conhecida por suas ales encorpadas e condimentadas.",
                            Name = "Abbaye de Leffe"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Bélgica",
                            Description = "Autêntica cervejaria trapista da Abadia de Scourmont, produzindo algumas das cervejas mais celebradas da Bélgica desde 1862.",
                            Name = "Brasserie Chimay"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Bélgica",
                            Description = "Cervejaria familiar fundada em 1871, mundialmente famosa pelo Duvel, uma forte ale dourada de aparência enganosa.",
                            Name = "Brasserie Duvel Moortgat"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Bélgica",
                            Description = "Cervejaria monacal trapista próxima a Antuérpia, criadora do estilo Tripel, produzindo desde 1836.",
                            Name = "Brouwerij Westmalle"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Bélgica",
                            Description = "Cervejaria trapista na Abadia de Saint-Remy, produzindo complexas ales escuras numeradas por sua densidade.",
                            Name = "Brasserie de Rochefort"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Bélgica",
                            Description = "Cervejaria independente fundada em 1906 em Melle, ícone da linha Delirium com o elefante rosa.",
                            Name = "Brouwerij Huyghe"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Bélgica",
                            Description = "Maior cervejaria do mundo, sediada em Leuven, lar de marcas globais icônicas como Stella Artois e Hoegaarden.",
                            Name = "AB InBev"
                        });
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<int>("BreweryId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WholesalerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("BreweryId");

                    b.HasIndex("WholesalerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Wholesaler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Wholesalers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rue du Marché aux Herbes 75, 1000 Brussels",
                            Name = "BeerWorld Brussels"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Grote Markt 12, 2000 Antwerp",
                            Name = "Belgian Beer Wholesale"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Meir 20, 2000 Antwerp",
                            Name = "Drinks & Co Antwerp"
                        });
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.WholesalerBeer", b =>
                {
                    b.Property<int>("WholesalerId")
                        .HasColumnType("int");

                    b.Property<int>("BeerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("WholesalerId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("WholesalerBeers");

                    b.HasData(
                        new
                        {
                            WholesalerId = 1,
                            BeerId = 1,
                            Quantity = 50
                        },
                        new
                        {
                            WholesalerId = 1,
                            BeerId = 4,
                            Quantity = 30
                        },
                        new
                        {
                            WholesalerId = 1,
                            BeerId = 7,
                            Quantity = 40
                        },
                        new
                        {
                            WholesalerId = 1,
                            BeerId = 15,
                            Quantity = 100
                        },
                        new
                        {
                            WholesalerId = 2,
                            BeerId = 5,
                            Quantity = 20
                        },
                        new
                        {
                            WholesalerId = 2,
                            BeerId = 10,
                            Quantity = 25
                        },
                        new
                        {
                            WholesalerId = 2,
                            BeerId = 13,
                            Quantity = 15
                        },
                        new
                        {
                            WholesalerId = 2,
                            BeerId = 14,
                            Quantity = 35
                        },
                        new
                        {
                            WholesalerId = 3,
                            BeerId = 3,
                            Quantity = 30
                        },
                        new
                        {
                            WholesalerId = 3,
                            BeerId = 8,
                            Quantity = 45
                        },
                        new
                        {
                            WholesalerId = 3,
                            BeerId = 12,
                            Quantity = 20
                        },
                        new
                        {
                            WholesalerId = 3,
                            BeerId = 16,
                            Quantity = 60
                        });
                });

            modelBuilder.Entity("BeerApi.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BreweryId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("WholesalerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("WholesalerId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Beer", b =>
                {
                    b.HasOne("BeerApi.Domain.Entities.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Sale", b =>
                {
                    b.HasOne("BeerApi.Domain.Entities.Beer", "Beer")
                        .WithMany("Sales")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeerApi.Domain.Entities.Brewery", "Brewery")
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeerApi.Domain.Entities.Wholesaler", "Wholesaler")
                        .WithMany()
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Brewery");

                    b.Navigation("Wholesaler");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.WholesalerBeer", b =>
                {
                    b.HasOne("BeerApi.Domain.Entities.Beer", "Beer")
                        .WithMany("WholesalerBeers")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerApi.Domain.Entities.Wholesaler", "Wholesaler")
                        .WithMany("WholesalerBeers")
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Wholesaler");
                });

            modelBuilder.Entity("BeerApi.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("BeerApi.Domain.Entities.Brewery", null)
                        .WithMany()
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeerApi.Domain.Entities.Wholesaler", null)
                        .WithMany()
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BeerApi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BeerApi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerApi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BeerApi.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Beer", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("WholesalerBeers");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Brewery", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("BeerApi.Domain.Entities.Wholesaler", b =>
                {
                    b.Navigation("WholesalerBeers");
                });
#pragma warning restore 612, 618
        }
    }
}
